### ISSUE TITLE
Membership

### ISSUE THREAD

**Issue by L4B0MB4** [EuropeOSS/join#1]
### What is your name?

Lars

### What do you do in the context of software?

I work as a fullstack developer. Currently a lot of React, NodeJS, C# and Go

### In which city of Europe are you based?

Stuttgart

###  What role do you see yourself playing in Europe OSS?

- [x] Active community member

### How can we reach you?

Twitter: @lars_0x4C

**Comment by lifenautjoe** [comment]
Welcome Lars! I've sent you an invite to the organization.

The initiative is still fresh. I've just created a discord channel to get things moving.

Let's start spreading the word around. Larger efforts will begin early 2020 with a website and some applications for research grants for projects that the community could propose.

https://discord.gg/Fab3B7

Remember to set your visibility to public here https://github.com/orgs/EuropeOSS/people .
